export type Airline = {
  accidents_last_5y: number,
  average_fleet_age: number,
  callsign: string,
  country_code: string,
  crashes_last_5y: number,
  email: string,
  facebook: string,
  iata_accounting: number,
  iata_code: string,
  iata_prefix: number,
  icao_code: string,
  instagram: string,
  iosa_registered: number,
  is_cargo: number,
  is_international: number,
  is_passenger: number,
  is_scheduled: number,
  kind: string,
  linkedin: string,
  name: string,
  phone: string,
  slug: string,
  total_aircrafts: number,
  twitter: string,
  updated: string,
  website: string,
}